# Platform
TARGET_BOARD_PLATFORM := sc7731c

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait
TARGET_BOARD_PLATFORM_GPU := mali400mp

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := SC7731C

# Kernel
TARGET_PREBUILT_KERNEL := device/Micromax/Q351/kernel
# TARGET_NO_KERNEL := true
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_SEPARATED_DT := true
BOARD_MKBOOTIMG_ARGS := --dt device/Micromax/Q351/dt.img --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE		:= 17825792
BOARD_RECOVERYIMAGE_PARTITION_SIZE	:= 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE	:= 2464153600
BOARD_CACHEIMAGE_PARTITION_SIZE		:= 157286400
BOARD_USERDATAIMAGE_PARTITION_SIZE	:= 4294967295
BOARD_MISCIMAGE_PARTITION_SIZE		:= 1048576
BOARD_FLASH_BLOCK_SIZE := 131072

# Enables RS driver
OVERRIDE_RS_DRIVER := libRSDriver.so

# Encryption
TW_INCLUDE_CRYPTO := true

# exFAT FS Support
TW_INCLUDE_FUSE_EXFAT := true

# NTFS Support
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_NTFS_3G := true

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
# LOCAL_CFLAGS += -DRECOVERY_ABGR
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_SUPPRESS_EMMC_WIPE := true

# TWRP
HAVE_SELINUX := true
TW_THEME := portrait_mdpi
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
TARGET_RECOVERY_FSTAB := device/Micromax/Q351/recovery.fstab
RECOVERY_FSTAB_VERSION := 2
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_HAS_NO_MISC_PARTITION := false
TW_IGNORE_MAJOR_AXIS_0 := false
#RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_FLASH_FROM_STORAGE := true
TW_DEFAULT_EXTERNAL_STORAGE := true
#TW_INTERNAL_STORAGE_PATH := /internal_sd
#TW_INTERNAL_STORAGE_MOUNT_POINT := internal_sd
TW_EXTERNAL_STORAGE_PATH := /external_sd
TW_EXTERNAL_STORAGE_MOUNT_POINT := external_sd
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_SUPERSU := true
#TW_EXCLUDE_ENCRYPTED_BACKUPS := true
#TW_DISABLE_TTF := true
TW_DEVICE_VERSION := v_5.3 *** Compiled by Kitaez71 ***

# USB Mounting
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/20200000.usb/gadget/lun%d/file